FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    python3 \
    pkg-config \
    autoconf \
    automake \
    libtool \
    libtool-bin \
    texinfo \
    gcc-multilib \
    g++-multilib \
    && rm -rf /var/lib/apt/lists/*
