FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    python3 \
    python3-serial \
    pkg-config \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi \
    qemu-system-arm \
    && rm -rf /var/lib/apt/lists/*
