FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    python3 \
    pkg-config \
    autoconf \
    libtool \
    libtool-bin \
    gcc-mipsel-linux-gnu \
    g++-mipsel-linux-gnu \
    libc6-mipsel-cross \
    && rm -rf /var/lib/apt/lists/*
